// Package capture loads the XDP program onto a network interface and
// delivers parsed DNS packets to a channel for downstream consumers.
package capture

import (
	"bytes"
	_ "embed"
	"fmt"
	"net"
	"os"
	"os/signal"
	"syscall"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/pathcl/dnswatch/internal/parser"
)

// bpfObject is the compiled XDP program embedded at build time.
// The binary is self-contained — no .o file needed at runtime.
//
//go:embed dns_capture.o
var bpfObject []byte

// Objects holds the loaded BPF maps and programs after the BPF object file
// is loaded into the kernel. Field names are generated by bpf2go and must
// match the SEC() and map names in dns_capture.c.
type Objects struct {
	DnsCapture *ebpf.Program `ebpf:"dns_capture"`
	Events     *ebpf.Map     `ebpf:"events"`
}

func (o *Objects) Close() {
	if o.DnsCapture != nil {
		o.DnsCapture.Close()
	}
	if o.Events != nil {
		o.Events.Close()
	}
}

// Run attaches the XDP program to iface and sends parsed DNS packets to out.
// Blocks until SIGINT or SIGTERM is received, then cleans up and returns.
func Run(iface string, out chan<- *parser.DNSPacket) error {
	// Load the BPF object from the embedded bytes.
	// bytes.NewReader implements io.ReaderAt, which LoadCollectionSpecFromReader requires.
	spec, err := ebpf.LoadCollectionSpecFromReader(bytes.NewReader(bpfObject))
	if err != nil {
		return fmt.Errorf("load bpf spec: %w", err)
	}

	objs := &Objects{}
	if err := spec.LoadAndAssign(objs, nil); err != nil {
		return fmt.Errorf("load bpf objects: %w", err)
	}
	defer objs.Close()

	// Attach XDP program to the network interface.
	// link.XDP tries native mode first, falls back to generic automatically.
	netIface, err := net.InterfaceByName(iface)
	if err != nil {
		return fmt.Errorf("interface %q not found: %w", iface, err)
	}

	xdpLink, err := link.AttachXDP(link.XDPOptions{
		Program:   objs.DnsCapture,
		Interface: netIface.Index,
	})
	if err != nil {
		return fmt.Errorf("attach xdp to %q: %w", iface, err)
	}
	defer xdpLink.Close()

	fmt.Fprintf(os.Stderr, "XDP attached to %s — capturing DNS traffic\n", iface)

	// Open ring buffer reader on the events map.
	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		return fmt.Errorf("open ring buffer: %w", err)
	}
	defer rd.Close()

	// Close the ring buffer reader on signal so rd.Read() unblocks and we exit.
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-sig
		rd.Close()
	}()

	for {
		record, err := rd.Read()
		if err != nil {
			// ringbuf.ErrClosed is returned when rd.Close() is called above.
			if err == ringbuf.ErrClosed {
				return nil
			}
			return fmt.Errorf("read ring buffer: %w", err)
		}

		pkt, err := parser.Parse(record.RawSample)
		if err != nil {
			// Malformed DNS packets are common (truncated, non-standard).
			// Log and continue rather than stopping the capture.
			fmt.Fprintf(os.Stderr, "parse error: %v\n", err)
			continue
		}

		out <- pkt
	}
}
